Better build process / Better makefile

diff --git a/Docker/Prod/dockerfile.application b/Docker/Prod/dockerfile.application
--- a/Docker/Prod/dockerfile.application
+++ b/Docker/Prod/dockerfile.application
@@ -1,5 +1,5 @@
 # Stage 1 - Build Frontend
-FROM node:22-alpine as frontend
+FROM node:22-alpine AS frontend
 
 ARG UID=1000
 ARG GID=1000
@@ -19,53 +19,44 @@ COPY ./.env .
 
 RUN chown -R node:node /app
 
-RUN npm run build
-RUN test -f /app/dist/index.html || (echo "Build failed !" && exit 1)
-
-
+RUN npm run build \
+    && test -f /app/dist/index.html || (echo "Build failed !" && exit 1)
 
 
 # Stage 2 - Build Backend-Frontend Hybrid App
-FROM php:8.2-fpm as application
+FROM php:8.2-fpm AS application
 
 ARG UID=1000
 ARG GID=1000
 
-RUN usermod -u ${UID} www-data
-RUN groupmod -g ${GID} www-data
-
-
-RUN apt-get update && apt-get install -y nano \
-    && rm -rf /var/lib/apt/lists/*
-
-RUN pecl install apcu \
-    && docker-php-ext-enable apcu
-
-RUN apt-get update \
+RUN usermod -u ${UID} www-data \
+    && groupmod -g ${GID} www-data \
+    # System tuning / utilities
+    && apt-get update \
     && apt-get install -y unzip git nano \
     && apt-get install -y libzip-dev libpng-dev libwebp-dev libjpeg-dev libfreetype-dev \
+    # PHP Extensions
     && docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype \
     && docker-php-ext-install pdo pdo_mysql zip gd exif \
-    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
-
-RUN echo "apc.enable_cli=1" > /usr/local/etc/php/conf.d/apcu.ini \
+    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
+    # PHP APCU Extension
+    && pecl install apcu \
+    && docker-php-ext-enable apcu \
+    && echo "apc.enable_cli=1" > /usr/local/etc/php/conf.d/apcu.ini \
     && echo "apc.enable=1"    >> /usr/local/etc/php/conf.d/apcu.ini \
-    && echo "chdir = /app/Public" >> /usr/local/etc/php-fpm.d/www.conf
-
-# Put sessions in a specific directory (which is linked to a volume)
-# Makes sessions persistents between restarts !
-RUN echo 'session.save_path = "/var/lib/php/sessions"' >> /usr/local/etc/php/conf.d/docker-session.ini \
+    && echo "chdir = /app/Public" >> /usr/local/etc/php-fpm.d/www.conf \
+    # Put sessions in a specific directory (which is linked to a volume)
+    # Makes sessions persistents between restarts !
+    && echo 'session.save_path = "/var/lib/php/sessions"' >> /usr/local/etc/php/conf.d/docker-session.ini \
     && mkdir -p /var/lib/php/sessions \
     && chown www-data:www-data /var/lib/php/sessions
 
 WORKDIR /app
 
 COPY ./composer.* .
-
 RUN composer install
 
 COPY . .
-
 COPY --from=frontend /app/dist ./frontend
 
 RUN chown -R www-data:www-data /app
